# 工作流名称:发布包到npmjs
name: Publish Package to npmjs

# 触发条件:当发布新的release时
on:
  release:
    types: [published]

# 定义工作流中的作业
jobs:
  build:
    # 指定运行环境
    runs-on: ubuntu-latest
    
    # 设置权限
    permissions:
      contents: read
      id-token: write
    
    # 定义作业的步骤
    steps:
      # 步骤1:检出代码
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 步骤2:设置Node.js环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: yarn install
      
      - name: Build
        run: yarn build
      
      # 步骤3:构建发布npm包
      - name: Publish package to npmjs
        run: npm publish --provenance --access public
        env:
          # 设置NPM认证token
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
